# JZ2440 Unified SDK Application Makefile
# Usage: make [V=1] [clean|all|flash|openocd|gdb]

TARGET    := $(notdir $(CURDIR))
TOP_DIR   := ../../..
TEXT_BASE := 0

# All magic happens in common.mk
include $(TOP_DIR)/common.mk
