# JZ2440 Unified SDK Application Makefile

TARGET    := 11_demo_lcd
TOP_DIR   := ../../..

# This application is designed to be loaded into SDRAM by the bootloader
ROM_ADDR   := 0x30000000
RAM_TARGET := sdram

include $(TOP_DIR)/common.mk
