# JZ2440 Unified SDK Application Makefile
# Usage: make [V=1] [clean|all|flash|openocd|gdb]

TARGET    := $(notdir $(CURDIR))
TOP_DIR   := ../../..
TEXT_BASE  := 0
START_FILE := $(TOP_DIR)/common/arch/demo_start.S
LDSCRIPT   := $(TOP_DIR)/common/lds/demo.lds

# All magic happens in common.mk
include $(TOP_DIR)/common.mk
